# SPDX-FileCopyrightText: 2023 Brian Kubisiak <brian@kubisiak.com>
#
# SPDX-License-Identifier: GPL-3.0-only

[tool.black]
line-length = 79

[tool.pylint.MAIN]
disable = [
    "R0903",  # too-few-public-methods
]