#!/bin/sh

# SPDX-FileCopyrightText: 2023 Brian Kubisiak <brian@kubisiak.com>
#
# SPDX-License-Identifier: GPL-3.0-only

set -e

VIRTUALENV=venv

if [ ! -d ${VIRTUALENV} ]; then
	python3 -m venv ${VIRTUALENV}
fi

. ${VIRTUALENV}/bin/activate

pip install --upgrade --requirement requirements.txt
